export const EDUCATION_TOPICS = [
  {
    id: 'medication', icon: '💊', color: '#8B5CF6',
    title: { en: 'Medication Guide', tl: 'Gabay sa Gamot', ceb: 'Giya sa Tambal', ilo: 'Giya iti Agas', war: 'Giya han Bulong' },
    content: {
      en: [
        'Always take medicine as prescribed by your doctor.',
        'Do not share your medicine with others.',
        'Store medicines in a cool, dry place away from children.',
        'Complete the full course of antibiotics even if you feel better.',
        'Tell your nurse if you experience side effects.',
        'Do not take expired medication.',
      ],
      tl: [
        'Laging inumin ang gamot ayon sa reseta ng doktor.',
        'Huwag ibahagi ang gamot sa iba.',
        'Itabi ang gamot sa malamig at tuyong lugar, malayo sa mga bata.',
        'Tapusin ang buong kurso ng antibiotics kahit bumuti na ang pakiramdam.',
        'Sabihin sa nars kung may side effects.',
        'Huwag uminom ng expired na gamot.',
      ],
      ceb: [
        'Kanunay imna ang tambal sumala sa reseta sa doktor.',
        'Ayaw ipaambit ang imong tambal sa uban.',
        'Tipigi ang tambal sa bugnaw ug uga nga lugar, layo sa mga bata.',
        'Humanon ang tibuok kurso sa antibiotics bisan og maayo na ang gibati.',
        'Sultihi ang nars kon naa kay side effects.',
        'Ayaw imna ang expired nga tambal.',
      ],
    },
  },
  {
    id: 'prenatal', icon: '🤰', color: '#F472B6',
    title: { en: 'Prenatal Care', tl: 'Pangangalaga Bago Manganak', ceb: 'Pag-atiman sa Buntis', ilo: 'Panangaywan iti Masikog', war: 'Pag-ataman han Buntis' },
    content: {
      en: [
        'Visit your doctor regularly during pregnancy.',
        'Take prenatal vitamins as prescribed.',
        'Eat nutritious food including vegetables and fruits.',
        'Avoid alcohol, smoking, and harmful substances.',
        'Get enough rest and sleep.',
        'Report any unusual symptoms immediately.',
      ],
      tl: [
        'Regular na bumisita sa doktor habang buntis.',
        'Uminom ng prenatal vitamins ayon sa reseta.',
        'Kumain ng masustansyang pagkain tulad ng gulay at prutas.',
        'Iwasan ang alak, paninigarilyo, at nakakapinsalang substances.',
        'Magpahinga at matulog nang sapat.',
        'I-report kaagad ang anumang hindi normal na sintomas.',
      ],
      ceb: [
        'Regular nga bisita sa doktor samtang buntis.',
        'Imna ang prenatal vitamins sumala sa reseta.',
        'Kaon og sustansya nga pagkaon sama sa utan ug prutas.',
        'Likayan ang bino, paninigarilyo, ug makadaut nga substances.',
        'Pagpahulay ug tulog og igo.',
        'I-report dayon ang bisan unsang dili normal nga sintomas.',
      ],
    },
  },
  {
    id: 'dengue', icon: '🦟', color: '#EF4444',
    title: { en: 'Dengue Prevention', tl: 'Pag-iwas sa Dengue', ceb: 'Paglikay sa Dengue', ilo: 'Panangliklik iti Dengue', war: 'Paglikay han Dengue' },
    content: {
      en: [
        'Remove stagnant water from containers around your home.',
        'Use mosquito nets and repellents.',
        'Wear long sleeves and pants.',
        'Clean your surroundings regularly.',
        'Seek medical help if you have high fever lasting 2+ days.',
        'Watch for warning signs: severe abdominal pain, persistent vomiting, bleeding.',
      ],
      tl: [
        'Alisin ang mga nakatigil na tubig sa mga lalagyan.',
        'Gumamit ng kulambo at mosquito repellent.',
        'Magsuot ng mahabang manggas at pantalon.',
        'Regular na linisin ang paligid.',
        'Humingi ng tulong medikal kung may mataas na lagnat ng 2+ araw.',
        'Bantayan ang mga warning signs: matinding sakit ng tiyan, tuloy-tuloy na pagsusuka, pagdurugo.',
      ],
      ceb: [
        'Kuhaa ang nagpundo nga tubig sa mga sudlanan.',
        'Gamita ang kulambo ug mosquito repellent.',
        'Pagsul-ob og taas nga manggas ug pantalon.',
        'Regular nga limpyohi ang palibot.',
        'Pangayo og medical help kon naa kay taas nga hilanat sulod sa 2+ ka adlaw.',
        'Bantayi ang mga warning signs: grabe nga sakit sa tiyan, padayon nga pagsuka, pagdugo.',
      ],
    },
  },
  {
    id: 'nutrition', icon: '🥗', color: '#10B981',
    title: { en: 'Nutrition Education', tl: 'Edukasyon sa Nutrisyon', ceb: 'Edukasyon sa Nutrisyon', ilo: 'Edukasyon iti Nutrisyon', war: 'Edukasyon han Nutrisyon' },
    content: {
      en: [
        'Eat a balanced diet with go, grow, and glow foods.',
        'Include vegetables and fruits in every meal.',
        'Drink at least 8 glasses of water daily.',
        'Limit consumption of processed and junk food.',
        'Breastfeed infants exclusively for the first 6 months.',
        'Avoid too much sugar, salt, and oil in food.',
      ],
      tl: [
        'Kumain ng balanced diet na may go, grow, at glow foods.',
        'Magsama ng gulay at prutas sa bawat kain.',
        'Uminom ng hindi bababa sa 8 baso ng tubig araw-araw.',
        'Limitahan ang pagkain ng processed at junk food.',
        'Exclusive breastfeeding sa unang 6 na buwan.',
        'Iwasan ang sobrang asukal, asin, at mantika.',
      ],
      ceb: [
        'Kaon og balanced diet nga naa ang go, grow, ug glow foods.',
        'Isama ang mga utan ug prutas sa matag kaon.',
        'Inom og labing menos 8 ka baso sa tubig adlaw-adlaw.',
        'Limitahi ang pagkaon og processed ug junk food.',
        'Exclusive breastfeeding sa unang 6 ka bulan.',
        'Likayan ang sobra nga asukal, asin, ug lana.',
      ],
    },
  },
  {
    id: 'hygiene', icon: '🧼', color: '#06B6D4',
    title: { en: 'Hygiene & Sanitation', tl: 'Kalinisan at Sanitasyon', ceb: 'Kahinlo ug Sanitasyon', ilo: 'Kinadalus ken Sanitasyon', war: 'Kalinisan ngan Sanitasyon' },
    content: {
      en: [
        'Wash hands with soap and water for at least 20 seconds.',
        'Take a bath daily.',
        'Brush your teeth at least twice a day.',
        'Keep your living area clean and organized.',
        'Properly dispose of garbage.',
        'Use clean water for drinking and cooking.',
      ],
      tl: [
        'Maghugas ng kamay gamit ang sabon at tubig nang hindi bababa sa 20 segundo.',
        'Maligo araw-araw.',
        'Magsipilyo ng ngipin hindi bababa sa dalawang beses sa isang araw.',
        'Panatilihing malinis at maayos ang bahay.',
        'Itapon nang maayos ang basura.',
        'Gumamit ng malinis na tubig para sa inumin at pagluluto.',
      ],
      ceb: [
        'Panghugas sa kamot gamit ang sabon ug tubig sulod sa labing menos 20 segundo.',
        'Paligo adlaw-adlaw.',
        'Pagsipilyo sa ngipon labing menos duha ka beses sa usa ka adlaw.',
        'Hinloi ug ayuha ang balay.',
        'Husay nga paglabay sa basura.',
        'Gamita ang limpyo nga tubig para sa ilimnon ug pagluto.',
      ],
    },
  },
  {
    id: 'firstaid', icon: '🩹', color: '#F59E0B',
    title: { en: 'Basic First Aid', tl: 'Pangunahing Lunas', ceb: 'Basic nga First Aid', ilo: 'Umuna nga Tulong', war: 'Basic nga First Aid' },
    content: {
      en: [
        'For minor cuts: Clean the wound with water, apply antiseptic, and cover with a bandage.',
        'For burns: Run cool water over the area for 10 minutes. Do not apply ice.',
        'For nosebleeds: Sit upright, lean forward, and pinch the nose for 10 minutes.',
        'For choking: Perform the Heimlich maneuver or call for help.',
        'For fainting: Lay the person flat, elevate the legs, and loosen tight clothing.',
        'Always call emergency services for severe injuries.',
      ],
      tl: [
        'Sa minor cuts: Linisin ang sugat ng tubig, lagyan ng antiseptic, at takpan ng bandage.',
        'Sa paso: Patakbuhin ang malamig na tubig sa apektadong bahagi ng 10 minuto.',
        'Sa pagdurugo ng ilong: Umupo nang tuwid, humiling pasulong, at kurutin ang ilong ng 10 minuto.',
        'Sa nababalunan: Gawin ang Heimlich maneuver o tumawag ng tulong.',
        'Sa nahimatay: Ihiga ang tao, itaas ang mga binti, at luwagan ang damit.',
        'Laging tumawag ng emergency services para sa matinding pinsala.',
      ],
      ceb: [
        'Sa gamay nga samad: Limpyohi ang samad og tubig, butangi og antiseptic, ug taboni og bendahe.',
        'Sa paso: Patubigi og bugnaw nga tubig ang dapit sulod sa 10 minuto.',
        'Sa pagdugo sa ilong: Lingkod og tul-id, hilig paabante, ug kusgon ang ilong sulod sa 10 minuto.',
        'Sa nalumos: Buhata ang Heimlich maneuver o tawag og tabang.',
        'Sa nahimatay: Pahigdaa ang taw, pataasa ang mga tiil, ug luaga ang biste.',
        'Kanunay tawag sa emergency services para sa grabe nga kadaut.',
      ],
    },
  },
];
