import { GoogleGenAI } from '@google/genai';
import { NextResponse } from 'next/server';

export async function POST(request) {
  try {
    const { text, langCode } = await request.json();

    if (!text) {
      return NextResponse.json({ error: 'Missing text' }, { status: 400 });
    }

    if (!process.env.GEMINI_API_KEY) {
      return NextResponse.json({ error: 'API key not configured' }, { status: 500 });
    }

    console.log(`[TTS API] Request for text: "${text.substring(0, 30)}..." (${langCode})`);

    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

    // Map language codes to voice names
    const voiceMap = {
      en: 'Kore',
      tl: 'Kore',
      ceb: 'Kore',
      ilo: 'Kore',
      war: 'Kore',
    };

    const voice = voiceMap[langCode] || 'Kore';

    const response = await ai.models.generateContent({
      model: 'gemini-3.1-flash-tts-preview',
      contents: text,
      config: {
        responseModalities: ['AUDIO'],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: {
              voiceName: voice,
            },
          },
        },
      },
    });

    // Extract audio data from response
    const audioData = response.candidates?.[0]?.content?.parts?.[0]?.inlineData;

    if (!audioData) {
      console.warn('[TTS API] No audio data returned from Gemini');
      return NextResponse.json({ error: 'No audio generated by AI' }, { status: 500 });
    }

    console.log(`[TTS API] Successfully generated audio: ${audioData.data.length} bytes`);

    // Convert base64 audio to buffer
    const audioBuffer = Buffer.from(audioData.data, 'base64');

    // Add WAV header for raw PCM data (Gemini returns 24kHz L16)
    const wavBuffer = addWavHeader(audioBuffer, 24000, 1, 16);

    return new Response(wavBuffer, {
      headers: {
        'Content-Type': 'audio/wav',
        'Content-Length': wavBuffer.length.toString(),
        'Cache-Control': 'public, max-age=31536000, immutable',
      },
    });
  } catch (error) {
    console.error('[TTS API] Error:', error.message || error);
    return NextResponse.json(
      { error: `TTS failed: ${error.message || 'Unknown error'}` },
      { status: 500 }
    );
  }
}

function addWavHeader(pcmData, sampleRate, numChannels, bitsPerSample) {
  const byteRate = sampleRate * numChannels * (bitsPerSample / 8);
  const blockAlign = numChannels * (bitsPerSample / 8);
  const dataSize = pcmData.length;
  const headerSize = 44;
  const buffer = Buffer.alloc(headerSize + dataSize);

  // RIFF header
  buffer.write('RIFF', 0);
  buffer.writeUInt32LE(36 + dataSize, 4);
  buffer.write('WAVE', 8);

  // fmt subchunk
  buffer.write('fmt ', 12);
  buffer.writeUInt32LE(16, 16);
  buffer.writeUInt16LE(1, 20); // PCM
  buffer.writeUInt16LE(numChannels, 22);
  buffer.writeUInt32LE(sampleRate, 24);
  buffer.writeUInt32LE(byteRate, 28);
  buffer.writeUInt16LE(blockAlign, 32);
  buffer.writeUInt16LE(bitsPerSample, 34);

  // data subchunk
  buffer.write('data', 36);
  buffer.writeUInt32LE(dataSize, 40);
  pcmData.copy(buffer, 44);

  return buffer;
}
